# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mind_tello.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1600, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1600, 950))
        MainWindow.setStyleSheet(_fromUtf8("QMainWindow {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.890995 rgba(0, 0, 0, 255), stop:1 rgba(135, 138, 143, 192))\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.logo_ubc = QtGui.QLabel(self.centralwidget)
        self.logo_ubc.setGeometry(QtCore.QRect(60, 830, 511, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney Book"))
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.logo_ubc.setFont(font)
        self.logo_ubc.setText(_fromUtf8(""))
        self.logo_ubc.setPixmap(QtGui.QPixmap(_fromUtf8("assets/1_2016_UBCStandard_Signature_ReverseRGB72.png")))
        self.logo_ubc.setScaledContents(True)
        self.logo_ubc.setObjectName(_fromUtf8("logo_ubc"))
        self.logo_nwhacks = QtGui.QLabel(self.centralwidget)
        self.logo_nwhacks.setGeometry(QtCore.QRect(1450, 800, 81, 111))
        self.logo_nwhacks.setText(_fromUtf8(""))
        self.logo_nwhacks.setPixmap(QtGui.QPixmap(_fromUtf8("assets/nwhacks.png")))
        self.logo_nwhacks.setScaledContents(True)
        self.logo_nwhacks.setObjectName(_fromUtf8("logo_nwhacks"))
        self.date = QtGui.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(60, 40, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney Book"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.date.setFont(font)
        self.date.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.date.setObjectName(_fromUtf8("date"))
        self.layoutWidget_15 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_15.setGeometry(QtCore.QRect(60, 130, 271, 151))
        self.layoutWidget_15.setObjectName(_fromUtf8("layoutWidget_15"))
        self.alpha_low_wave = QtGui.QVBoxLayout(self.layoutWidget_15)
        self.alpha_low_wave.setMargin(0)
        self.alpha_low_wave.setObjectName(_fromUtf8("alpha_low_wave"))
        self.layoutWidget_16 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_16.setGeometry(QtCore.QRect(360, 130, 271, 151))
        self.layoutWidget_16.setObjectName(_fromUtf8("layoutWidget_16"))
        self.alpha_high_wave = QtGui.QVBoxLayout(self.layoutWidget_16)
        self.alpha_high_wave.setMargin(0)
        self.alpha_high_wave.setObjectName(_fromUtf8("alpha_high_wave"))
        self.layoutWidget_17 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_17.setGeometry(QtCore.QRect(60, 360, 271, 151))
        self.layoutWidget_17.setObjectName(_fromUtf8("layoutWidget_17"))
        self.beta_low_wave = QtGui.QVBoxLayout(self.layoutWidget_17)
        self.beta_low_wave.setMargin(0)
        self.beta_low_wave.setObjectName(_fromUtf8("beta_low_wave"))
        self.layoutWidget_18 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_18.setGeometry(QtCore.QRect(360, 360, 271, 151))
        self.layoutWidget_18.setObjectName(_fromUtf8("layoutWidget_18"))
        self.beta_high_wave = QtGui.QVBoxLayout(self.layoutWidget_18)
        self.beta_high_wave.setMargin(0)
        self.beta_high_wave.setObjectName(_fromUtf8("beta_high_wave"))
        self.layoutWidget_19 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_19.setGeometry(QtCore.QRect(60, 590, 271, 151))
        self.layoutWidget_19.setObjectName(_fromUtf8("layoutWidget_19"))
        self.gamma_low_wave = QtGui.QVBoxLayout(self.layoutWidget_19)
        self.gamma_low_wave.setMargin(0)
        self.gamma_low_wave.setObjectName(_fromUtf8("gamma_low_wave"))
        self.layoutWidget_20 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_20.setGeometry(QtCore.QRect(360, 590, 271, 151))
        self.layoutWidget_20.setObjectName(_fromUtf8("layoutWidget_20"))
        self.gamma_mid_wave = QtGui.QVBoxLayout(self.layoutWidget_20)
        self.gamma_mid_wave.setMargin(0)
        self.gamma_mid_wave.setObjectName(_fromUtf8("gamma_mid_wave"))
        self.layoutWidget_21 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_21.setGeometry(QtCore.QRect(960, 560, 271, 181))
        self.layoutWidget_21.setObjectName(_fromUtf8("layoutWidget_21"))
        self.attention_wave = QtGui.QVBoxLayout(self.layoutWidget_21)
        self.attention_wave.setMargin(0)
        self.attention_wave.setObjectName(_fromUtf8("attention_wave"))
        self.layoutWidget_22 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_22.setGeometry(QtCore.QRect(1260, 560, 271, 181))
        self.layoutWidget_22.setObjectName(_fromUtf8("layoutWidget_22"))
        self.meditation_wave = QtGui.QVBoxLayout(self.layoutWidget_22)
        self.meditation_wave.setMargin(0)
        self.meditation_wave.setObjectName(_fromUtf8("meditation_wave"))
        self.layoutWidget_23 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_23.setGeometry(QtCore.QRect(960, 130, 571, 391))
        self.layoutWidget_23.setObjectName(_fromUtf8("layoutWidget_23"))
        self.device_display = QtGui.QVBoxLayout(self.layoutWidget_23)
        self.device_display.setMargin(0)
        self.device_display.setObjectName(_fromUtf8("device_display"))
        self.layoutWidget_24 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_24.setGeometry(QtCore.QRect(660, 130, 271, 151))
        self.layoutWidget_24.setObjectName(_fromUtf8("layoutWidget_24"))
        self.delta_wave = QtGui.QVBoxLayout(self.layoutWidget_24)
        self.delta_wave.setMargin(0)
        self.delta_wave.setObjectName(_fromUtf8("delta_wave"))
        self.layoutWidget_25 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_25.setGeometry(QtCore.QRect(660, 360, 271, 151))
        self.layoutWidget_25.setObjectName(_fromUtf8("layoutWidget_25"))
        self.theta_wave = QtGui.QVBoxLayout(self.layoutWidget_25)
        self.theta_wave.setMargin(0)
        self.theta_wave.setObjectName(_fromUtf8("theta_wave"))
        self.alpha_label = QtGui.QLabel(self.centralwidget)
        self.alpha_label.setGeometry(QtCore.QRect(60, 90, 571, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.alpha_label.setFont(font)
        self.alpha_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.alpha_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_label.setObjectName(_fromUtf8("alpha_label"))
        self.beta_label = QtGui.QLabel(self.centralwidget)
        self.beta_label.setGeometry(QtCore.QRect(60, 320, 571, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.beta_label.setFont(font)
        self.beta_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.beta_label.setAlignment(QtCore.Qt.AlignCenter)
        self.beta_label.setObjectName(_fromUtf8("beta_label"))
        self.gamma_label = QtGui.QLabel(self.centralwidget)
        self.gamma_label.setGeometry(QtCore.QRect(60, 550, 571, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gamma_label.setFont(font)
        self.gamma_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.gamma_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma_label.setObjectName(_fromUtf8("gamma_label"))
        self.alpha_low_data = QtGui.QLabel(self.centralwidget)
        self.alpha_low_data.setGeometry(QtCore.QRect(60, 280, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.alpha_low_data.setFont(font)
        self.alpha_low_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.alpha_low_data.setText(_fromUtf8(""))
        self.alpha_low_data.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_low_data.setObjectName(_fromUtf8("alpha_low_data"))
        self.alpha_high_data = QtGui.QLabel(self.centralwidget)
        self.alpha_high_data.setGeometry(QtCore.QRect(360, 280, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.alpha_high_data.setFont(font)
        self.alpha_high_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.alpha_high_data.setText(_fromUtf8(""))
        self.alpha_high_data.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_high_data.setObjectName(_fromUtf8("alpha_high_data"))
        self.beta_high_data = QtGui.QLabel(self.centralwidget)
        self.beta_high_data.setGeometry(QtCore.QRect(360, 510, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.beta_high_data.setFont(font)
        self.beta_high_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.beta_high_data.setText(_fromUtf8(""))
        self.beta_high_data.setAlignment(QtCore.Qt.AlignCenter)
        self.beta_high_data.setObjectName(_fromUtf8("beta_high_data"))
        self.beta_low_data = QtGui.QLabel(self.centralwidget)
        self.beta_low_data.setGeometry(QtCore.QRect(60, 510, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.beta_low_data.setFont(font)
        self.beta_low_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.beta_low_data.setText(_fromUtf8(""))
        self.beta_low_data.setAlignment(QtCore.Qt.AlignCenter)
        self.beta_low_data.setObjectName(_fromUtf8("beta_low_data"))
        self.gamma_low_data = QtGui.QLabel(self.centralwidget)
        self.gamma_low_data.setGeometry(QtCore.QRect(60, 740, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.gamma_low_data.setFont(font)
        self.gamma_low_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.gamma_low_data.setText(_fromUtf8(""))
        self.gamma_low_data.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma_low_data.setObjectName(_fromUtf8("gamma_low_data"))
        self.gamma_mid_data = QtGui.QLabel(self.centralwidget)
        self.gamma_mid_data.setGeometry(QtCore.QRect(360, 740, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.gamma_mid_data.setFont(font)
        self.gamma_mid_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.gamma_mid_data.setText(_fromUtf8(""))
        self.gamma_mid_data.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma_mid_data.setObjectName(_fromUtf8("gamma_mid_data"))
        self.delta_label = QtGui.QLabel(self.centralwidget)
        self.delta_label.setGeometry(QtCore.QRect(660, 90, 271, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.delta_label.setFont(font)
        self.delta_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.delta_label.setAlignment(QtCore.Qt.AlignCenter)
        self.delta_label.setObjectName(_fromUtf8("delta_label"))
        self.theta_label = QtGui.QLabel(self.centralwidget)
        self.theta_label.setGeometry(QtCore.QRect(660, 330, 271, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.theta_label.setFont(font)
        self.theta_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.theta_label.setAlignment(QtCore.Qt.AlignCenter)
        self.theta_label.setObjectName(_fromUtf8("theta_label"))
        self.delta_data = QtGui.QLabel(self.centralwidget)
        self.delta_data.setGeometry(QtCore.QRect(660, 280, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.delta_data.setFont(font)
        self.delta_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.delta_data.setText(_fromUtf8(""))
        self.delta_data.setAlignment(QtCore.Qt.AlignCenter)
        self.delta_data.setObjectName(_fromUtf8("delta_data"))
        self.theta_data = QtGui.QLabel(self.centralwidget)
        self.theta_data.setGeometry(QtCore.QRect(660, 510, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.theta_data.setFont(font)
        self.theta_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.theta_data.setText(_fromUtf8(""))
        self.theta_data.setAlignment(QtCore.Qt.AlignCenter)
        self.theta_data.setObjectName(_fromUtf8("theta_data"))
        self.tello_label = QtGui.QLabel(self.centralwidget)
        self.tello_label.setGeometry(QtCore.QRect(970, 80, 571, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney SemiboldSC"))
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.tello_label.setFont(font)
        self.tello_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.tello_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tello_label.setObjectName(_fromUtf8("tello_label"))
        self.attention_data = QtGui.QLabel(self.centralwidget)
        self.attention_data.setGeometry(QtCore.QRect(960, 740, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.attention_data.setFont(font)
        self.attention_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.attention_data.setText(_fromUtf8(""))
        self.attention_data.setAlignment(QtCore.Qt.AlignCenter)
        self.attention_data.setObjectName(_fromUtf8("attention_data"))
        self.meditation_data = QtGui.QLabel(self.centralwidget)
        self.meditation_data.setGeometry(QtCore.QRect(1260, 740, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.meditation_data.setFont(font)
        self.meditation_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.meditation_data.setText(_fromUtf8(""))
        self.meditation_data.setAlignment(QtCore.Qt.AlignCenter)
        self.meditation_data.setObjectName(_fromUtf8("meditation_data"))
        self.attention_label = QtGui.QLabel(self.centralwidget)
        self.attention_label.setGeometry(QtCore.QRect(960, 520, 271, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.attention_label.setFont(font)
        self.attention_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.attention_label.setAlignment(QtCore.Qt.AlignCenter)
        self.attention_label.setObjectName(_fromUtf8("attention_label"))
        self.meditation_label = QtGui.QLabel(self.centralwidget)
        self.meditation_label.setGeometry(QtCore.QRect(1260, 520, 271, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.meditation_label.setFont(font)
        self.meditation_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.meditation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.meditation_label.setObjectName(_fromUtf8("meditation_label"))
        self.rawdata_label = QtGui.QLabel(self.centralwidget)
        self.rawdata_label.setGeometry(QtCore.QRect(660, 560, 271, 37))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Whitney BookSC"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rawdata_label.setFont(font)
        self.rawdata_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.rawdata_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rawdata_label.setObjectName(_fromUtf8("rawdata_label"))
        self.raw_data = QtGui.QLabel(self.centralwidget)
        self.raw_data.setGeometry(QtCore.QRect(660, 740, 269, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.raw_data.setFont(font)
        self.raw_data.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: rgba(255,255,255,60);"))
        self.raw_data.setText(_fromUtf8(""))
        self.raw_data.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_data.setObjectName(_fromUtf8("raw_data"))
        self.layoutWidget_26 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_26.setGeometry(QtCore.QRect(660, 590, 271, 151))
        self.layoutWidget_26.setObjectName(_fromUtf8("layoutWidget_26"))
        self.rawdata_wave = QtGui.QVBoxLayout(self.layoutWidget_26)
        self.rawdata_wave.setMargin(0)
        self.rawdata_wave.setObjectName(_fromUtf8("rawdata_wave"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.date.setText(_translate("MainWindow", "Janurary 26, 2019", None))
        self.alpha_label.setText(_translate("MainWindow", "Alpha Magnitude", None))
        self.beta_label.setText(_translate("MainWindow", "Beta Magnitude", None))
        self.gamma_label.setText(_translate("MainWindow", "Gamma Magnitude", None))
        self.delta_label.setText(_translate("MainWindow", "Delta Magnitude", None))
        self.theta_label.setText(_translate("MainWindow", "Theta Magnitude", None))
        self.tello_label.setText(_translate("MainWindow", "Tello", None))
        self.attention_label.setText(_translate("MainWindow", "Attention", None))
        self.meditation_label.setText(_translate("MainWindow", "Meditation", None))
        self.rawdata_label.setText(_translate("MainWindow", "Raw Magnitude", None))

